theme: jekyll-theme-minimal
title: Petit cours d'épidémiologie mathématique
description: Un petit cours d'une vingtaine d'heures
show_downloads: true
site_favicon: /FIGS/favicon.ico
logo: /FIGS/plasmodium_entering_RBC.jpg
google_analytics: UA-1943806-8
plugins:
  - jekyll-sitemap
math_engine: mathjax
